version: '3'
services:
  app:
    build: .
    ports:
      - "${PORT:-5200}:${PORT:-5200}"
    volumes:
      - ./data:/app  # Stelle sicher, dass hier die licenses.db persistent gespeichert wird
    environment:
      - USERNAME=admin
      - PASSWORD=admin
      - BASE_DOMAIN=https://sonnystools.sonnyathome.online
      - UPLOAD_FOLDER=/app/uploads
      - PORT=5200
      - SECRET_KEY=123456
