version: '3'
services:
  app:
    build: .
    ports:
      - "${PORT:-5200}:${PORT:-5200}"
    volumes:
      - ./data:/data
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URI=sqlite:////data/licenses.db
      - UPLOAD_FOLDER=/app/uploads
      - PORT=5200
      - SECRET_KEY=123456
      - BASE_DOMAIN=https://localhost
      - USERNAME=admin
      - PASSWORD=admin
      -IP_MISMATCH_THRESHOLD=3
